import type {Meta,StoryObj} from '@storybook/react-vite';
import {useState} from 'react';
import {ChartDemo} from '../../../../packages/ui/src/complex/chart-demo.js';
const meta={title:'复杂/Chart 图表',component:ChartDemo} satisfies Meta<typeof ChartDemo>;
export default meta;
type Story=StoryObj<typeof meta>;
export const Playground:Story={args:{kind:'line',showLegend:true,showGrid:true,stacked:false,loading:false,error:''},argTypes:{kind:{control:'select',options:['line','area','bar','pie','donut']},showLegend:{control:'boolean'},showGrid:{control:'boolean'},stacked:{control:'boolean'},loading:{control:'boolean'},error:{control:'text'}},parameters:{controls:{include:['kind','showLegend','showGrid','stacked','loading','error']}}};
export const Bar:Story={args:{kind:'bar'}};
export const Area:Story={args:{kind:'area',stacked:true}};
export const Pie:Story={args:{kind:'pie'}};
export const Donut:Story={args:{kind:'donut'}};
export const Empty:Story={args:{data:[]}};
export const Loading:Story={args:{loading:true}};
export const Error:Story={args:{error:'本地数据加载失败'}};
export const NegativeValues:Story={args:{kind:'bar',data:[{id:'a',label:'净变化',values:{done:-10,pending:6}}]}};
export const InvalidData:Story={args:{kind:'pie',data:[{id:'a',label:'错误占比',values:{done:-10}}]}};
export const Retry:Story={render:function RetryDemo(){const [failed,setFailed]=useState(true);return <ChartDemo error={failed?'本地数据请求失败':undefined} onRetry={()=>setFailed(false)} />;}};
export const LongLabels:Story={args:{kind:'bar',data:[{id:'long-a',label:'桌面工作区组件一致性检查',values:{done:24,pending:12}},{id:'long-b',label:'键盘导航与辅助技术验证',values:{done:16,pending:8}}]}};
