import type {Meta,StoryObj} from '@storybook/react-vite';
import {SchedulerDemo} from '../../../../packages/ui/src/complex/scheduler-demo.js';
const meta={ id: "复杂-scheduler-排程",title:"复杂/Scheduler 排程",component:SchedulerDemo} satisfies Meta<typeof SchedulerDemo>;
export default meta;
type Story=StoryObj<typeof meta>;
export const Playground:Story={ name: "参数调试",args:{initialView:'week',readOnly:false,failSave:false,loading:false,empty:false},argTypes:{initialView:{control:'select',options:['day','week','month']},readOnly:{control:'boolean'},failSave:{control:'boolean'},loading:{control:'boolean'},empty:{control:'boolean'}},parameters:{controls:{include:['initialView','readOnly','failSave','loading','empty']}}};
export const Day:Story={ name: "视图 · 日",args:{initialView:'day'}};
export const Month:Story={ name: "视图 · 月",args:{initialView:'month'}};
export const ReadOnly:Story={ name: "状态 · 只读",args:{readOnly:true}};
export const SaveFailure:Story={ name: "状态 · 保存失败",args:{failSave:true}};
export const Empty:Story={ name: "状态 · 空内容",args:{empty:true}};
export const Loading:Story={ name: "状态 · 加载中",args:{loading:true}};
